#
# This is a basic generation workflow to create different output formats out of the md files stored in /src
#
 
name: Build Docs 

# Triggers the workflow on push events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build_pdf:
    runs-on: ubuntu-latest
    steps:

    # Checks-out the repository under $GITHUB_WORKSPACE
    - uses: actions/checkout@v2

    # Prepare the pandoc run
    - name: set md files as FILELIST
      run: |
        echo "::set-env name=FILELIST::$(printf '%s ' src/*.md)"

    # call a pandoc/latex docker container that is capable of processing the eisvogel template
    - uses: docker://thomasweise/docker-pandoc
      with:
        args: "pandoc --metadata-file=metadata/metadata.yml -t latex --data-dir=metadata --verbose --template=eisvogel --output=out/test.pdf --toc ${{ env.FILELIST }}" 

    # typically, workflows don't push results back into the same repo. This one does
    - name: Commit files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "Add changes" -a

    # results are pushed back into the out directory of this repo.
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}

  build_docx:
    runs-on: ubuntu-latest
    steps:

    # Checks-out the repository under $GITHUB_WORKSPACE
    - uses: actions/checkout@v2

    # Prepare the pandoc run
    - name: set md files as FILELIST
      run: |
        echo "::set-env name=FILELIST::$(printf '%s ' src/*.md)"

    # call a pandoc/latex docker container that is capable of processing the eisvogel template
    - uses: docker://thomasweise/docker-pandoc
      with:
        args: "pandoc --metadata-file=metadata/metadata.yml -t docx --data-dir=metadata --verbose --template=eisvogel --output=out/test.docx --toc ${{ env.FILELIST }}" 

    # typically, workflows don't push results back into the same repo. This one does
    - name: Commit files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "Add changes" -a

    # results are pushed back into the out directory of this repo.
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
